<?php
/**********************************************************
 *
 * File:         Custom Post Types
 * Description:  Register the custom post types
 * Author:       Echo Web Solutions
 * Version:      v0.1
 * Modified:
 *
 **********************************************************/
defined('ABSPATH') or die('No script kiddies please!');

add_action('init', function () {

	register_post_type('echo_reviews', array(
		'labels' => array(
			'name' => 'Reviews',
			'singular_name' => 'Reviews',
			'menu_name' => 'Reviews',
			'all_items' => 'All Reviews',
			'edit_item' => 'Edit Review',
			'view_item' => 'View Review',
			'view_items' => 'View Reviews',
			'add_new_item' => 'Add New Review',
			'new_item' => 'New Review',
			'parent_item_colon' => 'Parent Review:',
			'search_items' => 'Search Reviews',
			'not_found' => 'No Reviews found',
			'not_found_in_trash' => 'No Reviews found in the bin',
			'archives' => 'Review Archives',
			'attributes' => 'Review Attributes',
			'insert_into_item' => 'Insert into Review',
			'uploaded_to_this_item' => 'Uploaded to this Review',
			'filter_items_list' => 'Filter Reviews list',
			'filter_by_date' => 'Filter Reviews by date',
			'items_list_navigation' => 'Reviews list navigation',
			'items_list' => 'Reviews list',
			'item_published' => 'Review published.',
			'item_published_privately' => 'Review published privately.',
			'item_reverted_to_draft' => 'Review reverted to draft.',
			'item_scheduled' => 'Review scheduled.',
			'item_updated' => 'Review updated.',
			'item_link' => 'Review Link',
			'item_link_description' => 'A link to a Review.',
		),
		'public' => true,
		'exclude_from_search' => false,
		'show_in_nav_menus' => false,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-star-half',
		'supports' => array(
			0 => 'title',
			1 => 'excerpt',
			2 => 'editor',
			3 => 'thumbnail',
		),
		'has_archive' => 'reviews',
		'rewrite' => array(
			'slug' => 'reviews',
			'with_front' => false,
			'pages' => true,
		),
		'can_export' => false,
		'delete_with_user' => false,
	));

	register_post_type('echo_teams', array(
		'labels' => array(
			'name' => 'Team Members',
			'singular_name' => 'Team Member',
			'menu_name' => 'Team Members',
			'all_items' => 'All Team Members',
			'edit_item' => 'Edit Team Member',
			'view_item' => 'View Team Member',
			'view_items' => 'View Team Members',
			'add_new_item' => 'Add New Team Member',
			'new_item' => 'New Team Member',
			'parent_item_colon' => 'Parent Team Member:',
			'search_items' => 'Search Team Members',
			'not_found' => 'No Team Members found',
			'not_found_in_trash' => 'No Team Members found in the bin',
			'archives' => 'Team Member Archives',
			'attributes' => 'Team Member Attributes',
			'insert_into_item' => 'Insert into Team Member',
			'uploaded_to_this_item' => 'Uploaded to this Team Member',
			'filter_items_list' => 'Filter Team Members list',
			'filter_by_date' => 'Filter Team Members by date',
			'items_list_navigation' => 'Team Members list navigation',
			'items_list' => 'Team Members list',
			'item_published' => 'Team Member published.',
			'item_published_privately' => 'Team Member published privately.',
			'item_reverted_to_draft' => 'Team Member reverted to draft.',
			'item_scheduled' => 'Team Member scheduled.',
			'item_updated' => 'Team Member updated.',
			'item_link' => 'Team Member Link',
			'item_link_description' => 'A link to a Team Member.',
		),
		'public' => true,
		'exclude_from_search' => false,
		'show_in_nav_menus' => false,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-admin-users',
		'supports' => array(
			0 => 'title',
			1 => 'excerpt',
			2 => 'editor',
			3 => 'thumbnail',
		),
		'has_archive' => false,
		'rewrite' => array(
			'slug' => 'teams',
			'with_front' => false,
			'pages' => true,
		),
		'can_export' => false,
		'delete_with_user' => false,
	));

	register_post_type('echo_careers', array(
		'labels' => array(
			'name' => 'Careers',
			'singular_name' => 'Career',
			'menu_name' => 'Careers',
			'all_items' => 'All Careers',
			'edit_item' => 'Edit Career',
			'view_item' => 'View Career',
			'view_items' => 'View Careers',
			'add_new_item' => 'Add New Career',
			'new_item' => 'New Career',
			'parent_item_colon' => 'Parent Career:',
			'search_items' => 'Search Careers',
			'not_found' => 'No Careers found',
			'not_found_in_trash' => 'No Careers found in the bin',
			'archives' => 'Career Archives',
			'attributes' => 'Career Attributes',
			'insert_into_item' => 'Insert into Career',
			'uploaded_to_this_item' => 'Uploaded to this Career',
			'filter_items_list' => 'Filter Careers list',
			'filter_by_date' => 'Filter Careers by date',
			'items_list_navigation' => 'Careers list navigation',
			'items_list' => 'Careers list',
			'item_published' => 'Career published.',
			'item_published_privately' => 'Career published privately.',
			'item_reverted_to_draft' => 'Career reverted to draft.',
			'item_scheduled' => 'Career scheduled.',
			'item_updated' => 'Career updated.',
			'item_link' => 'Career Link',
			'item_link_description' => 'A link to a Career.',
		),
		'public' => true,
		'exclude_from_search' => false,
		'show_in_nav_menus' => false,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-book',
		'supports' => array(
			0 => 'title',
		),
		'has_archive' => false,
		'rewrite' => array(
			'slug' => 'careers',
			'with_front' => false,
			'pages' => true,
		),
		'can_export' => false,
		'delete_with_user' => false,
	));

	register_taxonomy('service_category', array('echo_services'), array(
		'labels' => array(
			'name' => 'Service Categories',
			'singular_name' => 'Service Category',
			'search_items' => 'Search Service Categories',
			'all_items' => 'All Service Categories',
			'parent_item' => 'Parent Service Category',
			'parent_item_colon' => 'Parent Service Category:',
			'edit_item' => 'Edit Service Category',
			'update_item' => 'Update Service Category',
			'add_new_item' => 'Add New Service Category',
			'new_item_name' => 'New Service Category Name',
			'menu_name' => 'Service Categories',
		),
		'hierarchical' => true,
		'show_ui' => true,
		'show_admin_column' => true,
		'query_var' => true,
		'rewrite' => array(
			'slug' => 'services', // your category URL base
			'with_front' => false,
			'hierarchical' => true,
		),
		'show_in_rest' => true, // enables Gutenberg + REST API
	));

	register_post_type('echo_services', array(
		'labels' => array(
			'name' => 'Services',
			'singular_name' => 'Service',
			'menu_name' => 'Services',
			'all_items' => 'All Services',
			'edit_item' => 'Edit Service',
			'view_item' => 'View Service',
			'view_items' => 'View Services',
			'add_new_item' => 'Add New Service',
			'new_item' => 'New Service',
			'parent_item_colon' => 'Parent Service:',
			'search_items' => 'Search Services',
			'not_found' => 'No Services found',
			'not_found_in_trash' => 'No Services found in the bin',
			'archives' => 'Service Archives',
			'attributes' => 'Service Attributes',
			'insert_into_item' => 'Insert into Service',
			'uploaded_to_this_item' => 'Uploaded to this Service',
			'filter_items_list' => 'Filter Services list',
			'filter_by_date' => 'Filter Services by date',
			'items_list_navigation' => 'Services list navigation',
			'items_list' => 'Services list',
			'item_published' => 'Service published.',
			'item_published_privately' => 'Service published privately.',
			'item_reverted_to_draft' => 'Service reverted to draft.',
			'item_scheduled' => 'Service scheduled.',
			'item_updated' => 'Service updated.',
			'item_link' => 'Service Link',
			'item_link_description' => 'A link to a Service.',
		),
		'public' => true,
		'exclude_from_search' => false,
		'show_in_nav_menus' => false,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-schedule',
		'supports' => array(
			0 => 'title',
			1 => 'excerpt',
			2 => 'editor',
			3 => 'thumbnail',
		),
		'taxonomies' => array('service_category'),
		'has_archive' => 'services',
		'rewrite' => array(
			'slug' => 'services/%service_category%',
			'with_front' => false,
			'pages' => true,
		),
		'can_export' => false,
		'delete_with_user' => false,
	));
});
